_wandb:
    value:
        cli_version: 0.23.1
        e:
            zph1htujtgfmymg3phujtvpi1oby7aur:
                codePath: train.py
                codePathLocal: train.py
                cpu_count: 2
                cpu_count_logical: 4
                disk:
                    /:
                        total: "107725451264"
                        used: "45411254272"
                email: sumitrwk@gmail.com
                executable: D:\tiny-llm-model\venv\Scripts\python.exe
                git:
                    commit: 06329fb92c7a89b94ffe8c108df987059e1d6cd4
                    remote: https://github.com/sumitrwk90/tiny-llm-model.git
                host: venom
                memory:
                    total: "17028448256"
                os: Windows-10-10.0.19045-SP0
                program: D:\tiny-llm-model\train.py
                python: CPython 3.12.1
                root: D:\tiny-llm-model
                startedAt: "2026-01-09T08:00:22.824108Z"
                writerId: zph1htujtgfmymg3phujtvpi1oby7aur
        m: []
        python_version: 3.12.1
        t:
            "1":
                - 2
                - 1
                - 3
                - 11
                - 49
                - 51
            "2":
                - 2
                - 1
                - 3
                - 11
                - 49
                - 51
            "3":
                - 13
                - 16
            "4": 3.12.1
            "5": 0.23.1
            "6": 4.57.1
            "8":
                - 3
            "12": 0.23.1
            "13": windows-amd64
accumulate_grad:
    value: 4
activation_checkpointing:
    value: true
batch_size:
    value: 4
betas:
    value:
        - 0.9
        - 0.95
dataset_name:
    value: the-verdict
ddp:
    value: false
device:
    value: cuda
eval_interval:
    value: 500
grad_clip:
    value: 1
learning_rate:
    value: 0.0003
max_iters:
    value: 10000
max_steps:
    value: 100
out_dir:
    value: ./checkpoints
resume_path:
    value: ckpt.pt
weight_decay:
    value: 0.1
